name: CI
on: push
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v4
        with:
    node-version: 18
      - run: npm ci
      - run: npm run build    
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Use node 
          uses: actions/setup-node@v4
          with:
      node-version: 18
        - run: npm ci   
        - run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: testnet
      url: ${{ steps.deployment.outputs.contractId }}
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Use node 
          uses: actions/setup-node@v4
          with:
      node-version: 18
        - run: npm ci   
        - run: npm run build
        - name: deploy
          id: deployment
          uses: nomadic-labs/tezosX-deploy@v0.0.1
          with:
    sk: ${{ secrets.SK }}
    user: ${{ env.PKH }}
    file: dist/index.js
    rpc: ${{ env.TEZOSX_URL }}
    balance: 0
    gas-limit: 1000000
    name: polymarktez
    runtime: jstz
    instances: 2
    memory: 256M
    cpu: standard-1
    region: eu
  build-pages:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
    - uses: actions/checkout@v4
    - name: Install mdBook
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
        rustup update
        cargo install --version ${MDBOOK_VERSION} mdbook
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with mdBook
      run: mdbook build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./book
      
# Deployment job
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-pages
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4    